language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

services:
 - mysql

# Set up a test database we can use for the the unit tests
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS simplesamlphp;'
  - mysql -e 'CREATE TABLE IF NOT EXISTS `AttributeFromSQL` (
        `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
        `uid` VARCHAR(100) NOT NULL,
        `sp` VARCHAR(250) DEFAULT "%",
        `attribute` VARCHAR(30) NOT NULL,
        `value` TEXT,
        `expires` DATE DEFAULT "9999-12-31",
        PRIMARY KEY (`id`)
    ) DEFAULT CHARSET=utf8;
    GRANT ALL ON `simplesamlphp`.* TO `phpunit`@`localhost` IDENTIFIED BY "phpunit";
    ' simplesamlphp
  - mysql -e "
    INSERT INTO AttributeFromSQL (uid, sp, attribute, value) VALUES ('user@example.org', '%', 'eduPersonEntitlement', 'urn:mace:exampleIdP.org:demoservice:demo-admin');
    INSERT INTO AttributeFromSQL (uid, sp, attribute, value) VALUES ('user@example.org', 'https://idp.example.org/idp/shibboleth', 'eduPersonEntitlement', 'urn:mace:grnet.gr:eduroam:admin');
    INSERT INTO AttributeFromSQL (uid, sp, attribute, value) VALUES ('user@example.org', '%', 'eduPersonAffiliation', 'faculty');
    INSERT INTO AttributeFromSQL (uid, attribute, value) VALUES ('user@example.org', 'mail', 'user@example.org');
    INSERT INTO AttributeFromSQL (uid, attribute, value, expires) VALUES ('user@example.org', 'mail', 'marty@example.org', '2015-10-21');
    " simplesamlphp

before_script:
  - composer update
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then composer require --dev vimeo/psalm:1.1.9; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then composer require --dev php-coveralls/php-coveralls; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/phpunit/phpunit/phpunit; else php vendor/phpunit/phpunit/phpunit --no-coverage; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then vendor/bin/psalm; fi

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/bin/php-coveralls -v; fi

